#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page.

apt-get update
apt-get -y install nginx
display="Hello World!"
echo "$display" > /var/www/html/index.html
echo "server {
        listen 80 default_server;
        server_name _;

        location /redirect_me {
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }
	location / {
		root /var/www/html;
		index index.html index.htm index.nginx-debian.html;
	}
}" > /etc/nginx/sites-available/default

service nginx restart
