#!/usr/bin/env bash
# Configure Nginx server to have a custom 404 page that contains the string

# Update package list
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Create a custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# display a page hello world with a GET request
display="Hello World!"
echo "$display" > /var/www/html/index.html

# Configure Nginx for custom 404 page
echo "server {
	listen 80;
	server_name localhost;

	location /redirect_me {
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;	
	}

	location / {
		root /var/www/html;
		index index.html index.htm index.nginx-debian.html;
	}

	error_page 404 /404.html;
	location = /404.html {
		root /var/www/html;
		internal;
	}
}" > /etc/nginx/sites-available/default

# Restart Nginx (without using systemctl)
service nginx restart
