#!/usr/bin/env bash
# To install and configure HAProxy on lb-01 sever

sudo apt-get update
sudo apt-get install -y haproxy

#configure HAProxy to send traffic to web-01 and web-02
#using roundrobin algorithm
conf="
backend http_backend
	balance roundrobin
	server 180709-web-01 54.167.92.84:80 check
	server 180709-web-02 35.175.128.43:80 check

frontend http_frontend
	bind *:80
	mode http
	default_backend http_backend"
	
sudo echo "$conf" >> /etc/haproxy/haproxy.cfg
# Make HAProxy to be managed via init script
sudo systemctl enable haproxy
# restart haproxy to effect changes
sudo service haproxy restart
