#!/usr/bin/env bash
#Dispaly Best School 10 time, but for the 9th iteration, display Best School and then Hi

x=0
while [ $x -lt 10 ]
do
	echo "Best School"
	if [ $x -eq 8 ]
	then
		echo "Hi"
	fi
	((x=x+1))
done
