#!/usr/bin/env bash
#Write a Bash script that configures an Ubuntu server with the below requirements.

# Requirements:

# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.

cp /etc/hosts ~/hosts.txt
sed "s/127.0.0.1/127.0.0.2/" ~/hosts.txt
echo "8.8.8.8 facebook.com" >> ~/hosts.txt
cp -f ~/hosts.txt /etc/hosts
